### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by jakob85** [mandubian/scala-xmlsoap-ersatz#3]
Hi there! I'm trying to add the lib to my play 2.2.0 app but I'm having trouble downloading the dependecy.

[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play2.tools.xml#xmlsoap-ersatz_2.10;0.2-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: play2.tools.xml#xmlsoap-ersatz_2.10;0.2-SNAPSHOT: not found
...
[error] Missing task key: scalaInstance
java.lang.IllegalArgumentException

My build.sbt

version := "1.1-SNAPSHOT"

libraryDependencies ++= Seq(
  cache,
  "securesocial" %% "securesocial" % "2.1.2",
  "org.reactivemongo" %% "play2-reactivemongo" % "0.10.0",
  "play2.tools.xml" %% "xmlsoap-ersatz" % "0.2-SNAPSHOT"
)

scalaVersion := "2.10.2"

resolvers ++= Seq(
Resolver.url("mandubian-mvn snapshots", url("http://github.com/mandubian/mandubian-mvn/raw/master/snapshots")),
Resolver.url("Sonatype snapshots", url("http://oss.sonatype.org/content/repositories/snapshots/")),
Resolver.url("typesafe", url("http://repo.typesafe.com/typesafe/repo")),
Resolver.url("typesafe-community", url("http://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/"))(Resolver.ivyStylePatterns),
Resolver.url("typesafe-community-snapshots", url("http://repo.scala-sbt.org/scalasbt/sbt-plugin-snapshots/"))(Resolver.ivyStylePatterns)
)

play.Project.playScalaSettings

I'm probably missing something really simple?
Thank you.

**Comment by mchv** [comment]
I think the problem comes from the mismatch bewteen the scala vesion you are using (2.10) and the scala version this module has been compiled (2.9.1)

**Comment by mandubian** [comment]
I've just published on my fake mvn a version 0.2 (without snapshot) for scala 2.10!

**Comment by jakob85** [comment]
Amazing!
Still not sure how I should write in my build.sbt though =)

"play2.tools.xml" %% "xmlsoap-ersatz" % "0.2"
and
resolvers ++= Seq(
Resolver.url("mandubian-mvn", url("http://github.com/mandubian/mandubian-mvn/raw/master/releases")),
still gives me 
warn]   ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: play2.tools.xml#xmlsoap-ersatz_2.10;0.2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

Any pointers on that?
Best regards,
Jakob

**Comment by poornerd** [comment]
I have this problem, too - any tips anyone on how to solve?

**Comment by neowinx** [comment]
Well, haven't try myself, but you could specify your scala version adding something like:

``` scala
scalaVersion := "2.10.6"
```

to your **build.sbt**. An example could be:

``` scala
name := """my-project"""

version := "1.0-SNAPSHOT"

lazy val root = (project in file(".")).enablePlugins(PlayScala)

scalaVersion := "2.10.6"

libraryDependencies ++= Seq(
  cache,
  ws, 
  evolutions,
  specs2 % Test,
  "postgresql" % "postgresql" % "9.1-901-1.jdbc4",
  "com.typesafe.play" %% "play-slick" % "1.0.1",
  "com.typesafe.play" %% "play-slick-evolutions" % "1.0.1",
  "org.postgresql" % "postgresql" % "9.4-1205-jdbc42",
  "com.wordnik" %% "swagger-play2" % "1.3.13",
  "org.scala-lang" % "scala-reflect" % "2.10.6",
  "play2.tools.xml" %% "xmlsoap-ersatz" % "0.2"
)

resolvers += "scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"

resolvers += Resolver.url("mandubian-mvn", url("http://github.com/mandubian/mandubian-mvn/raw/master/releases")

resolvers ++= Seq("snapshots", "releases").map(Resolver.sonatypeRepo)
```

Regards!

neowinx
